import type {
  AttentionCounts,
  AttentionOrder,
  AttentionQueueResponse,
  AttentionReason,
  BulkOrderResult,
} from '@/types/attention'
import type { AttentionQueueParams } from '@/services/attention.service'

const now = new Date()

const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString()

let mockOrders: AttentionOrder[] = [
  {
    id: 'mock-order-001',
    orderName: '#ALK-1048',
    customerName: 'Aminata Diop',
    customerPhone: '+221 77 245 19 88',
    region: 'Dakar',
    amount: { value: '34500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Bonjour, je confirme mais je veux etre livree demain apres 16h si possible.',
    receivedAt: minutesAgo(18),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-002',
    orderName: '#ALK-1047',
    customerName: 'Mouhamadou Fall',
    customerPhone: '+221 76 611 04 90',
    region: 'Thies',
    amount: { value: '22000', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(54),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-003',
    orderName: '#ALK-1046',
    customerName: 'Fatou Ndiaye',
    customerPhone: '',
    region: 'Saint-Louis',
    amount: { value: '18750', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'invalid_number',
    lastCustomerMessage: 'Numero Shopify invalide: 00221771234567',
    receivedAt: minutesAgo(93),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-004',
    orderName: '#ALK-1045',
    customerName: 'Ousmane Sarr',
    customerPhone: '+221 78 302 66 41',
    region: 'Dakar',
    amount: { value: '51000', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme maintenant, desole pour le retard.',
    receivedAt: minutesAgo(138),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-005',
    orderName: '#ALK-1044',
    customerName: 'Marieme Ba',
    customerPhone: '+221 77 900 41 33',
    region: 'Mbour',
    amount: { value: '12900', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je ne serai pas a cette adresse. Appelez-moi avant expedition.',
    receivedAt: minutesAgo(210),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-006',
    orderName: '#ALK-1043',
    customerName: 'Cheikh Gueye',
    customerPhone: '+221 70 124 08 77',
    region: 'Kaolack',
    amount: { value: '76000', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(322),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-007',
    orderName: '#ALK-1042',
    customerName: 'Ndeye Gueye',
    customerPhone: '+221 78 612 34 44',
    region: 'Dakar',
    amount: { value: '39500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'C est pour un cadeau, ne mettez pas la facture dans le colis.',
    receivedAt: minutesAgo(405),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-008',
    orderName: '#ALK-1041',
    customerName: 'Ibrahima Kane',
    customerPhone: '',
    region: 'Louga',
    amount: { value: '9850', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'invalid_number',
    lastCustomerMessage: 'Telephone manquant dans Shopify.',
    receivedAt: minutesAgo(480),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-009',
    orderName: '#ALK-1040',
    customerName: 'Sokhna Ly',
    customerPhone: '+221 76 403 22 10',
    region: 'Ziguinchor',
    amount: { value: '44000', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Oui je confirme, je viens de voir le message.',
    receivedAt: minutesAgo(610),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-010',
    orderName: '#ALK-1039',
    customerName: 'Alioune Mbaye',
    customerPhone: '+221 75 932 11 60',
    region: 'Dakar',
    amount: { value: '26500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(780),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-011',
    orderName: '#ALK-1038',
    customerName: 'Bineta Sow',
    customerPhone: '+221 77 511 72 00',
    region: 'Diourbel',
    amount: { value: '15200', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je veux changer la couleur vers noir si disponible.',
    receivedAt: minutesAgo(940),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-012',
    orderName: '#ALK-1037',
    customerName: 'Mamadou Diallo',
    customerPhone: '+221 70 881 14 59',
    region: 'Dakar',
    amount: { value: '68000', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme, vous pouvez expedier.',
    receivedAt: minutesAgo(1_160),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-013',
    orderName: '#ALK-1036',
    customerName: 'Astou Camara',
    customerPhone: '+221 77 382 29 71',
    region: 'Dakar',
    amount: { value: '29900', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je confirme, mais envoyez le colis a mon bureau a Almadies plutot que chez moi.',
    receivedAt: minutesAgo(1_260),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-014',
    orderName: '#ALK-1035',
    customerName: 'Babacar Seck',
    customerPhone: '+221 76 850 94 22',
    region: 'Rufisque',
    amount: { value: '118500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(1_380),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-015',
    orderName: '#ALK-1034',
    customerName: 'Maimouna Cisse',
    customerPhone: '',
    region: 'Tambacounda',
    amount: { value: '7400', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'invalid_number',
    lastCustomerMessage: 'Numero trop court: 771234',
    receivedAt: minutesAgo(1_530),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-016',
    orderName: '#ALK-1033',
    customerName: 'El Hadji Faye',
    customerPhone: '+221 77 018 47 85',
    region: 'Dakar',
    amount: { value: '91000', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Confirmation recue apres expiration automatique.',
    receivedAt: minutesAgo(1_720),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-017',
    orderName: '#ALK-1032',
    customerName: 'Khady Tall',
    customerPhone: '+221 70 442 18 39',
    region: 'Keur Massar',
    amount: { value: '32500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je confirme seulement si la livraison est gratuite comme indique par la vendeuse.',
    receivedAt: minutesAgo(1_830),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-018',
    orderName: '#ALK-1031',
    customerName: 'Serigne Ndiaye',
    customerPhone: '+221 78 749 63 12',
    region: 'Touba',
    amount: { value: '58400', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(1_940),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-019',
    orderName: '#ALK-1030',
    customerName: 'Coumba Gueye',
    customerPhone: '+221 77 618 50 02',
    region: 'Pikine',
    amount: { value: '45600', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Est-ce que je peux payer une partie maintenant et le reste a la livraison ?',
    receivedAt: minutesAgo(2_060),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-020',
    orderName: '#ALK-1029',
    customerName: 'Abdoulaye Sy',
    customerPhone: '',
    region: 'Fatick',
    amount: { value: '16200', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'invalid_number',
    lastCustomerMessage: 'Indicatif absent dans le telephone Shopify.',
    receivedAt: minutesAgo(2_220),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-021',
    orderName: '#ALK-1028',
    customerName: 'Dieynaba Diagne',
    customerPhone: '+221 76 719 35 48',
    region: 'Dakar',
    amount: { value: '64000', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme, mon paiement Wave est deja fait.',
    receivedAt: minutesAgo(2_360),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-022',
    orderName: '#ALK-1027',
    customerName: 'Modou Lo',
    customerPhone: '+221 75 804 71 93',
    region: 'Guediawaye',
    amount: { value: '20300', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je ne confirme pas encore, je dois verifier la taille avec mon frere.',
    receivedAt: minutesAgo(2_510),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-023',
    orderName: '#ALK-1026',
    customerName: 'Awa Sene',
    customerPhone: '+221 77 459 82 61',
    region: 'Mbour',
    amount: { value: '37900', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(2_670),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-024',
    orderName: '#ALK-1025',
    customerName: 'Pape Demba Ba',
    customerPhone: '',
    region: 'Matam',
    amount: { value: '88500', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'invalid_number',
    lastCustomerMessage: 'Numero contient des caracteres non valides.',
    receivedAt: minutesAgo(2_840),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-025',
    orderName: '#ALK-1024',
    customerName: 'Rokhaya Thiam',
    customerPhone: '+221 78 225 49 30',
    region: 'Dakar',
    amount: { value: '55500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Merci de garder la commande. Je peux recevoir samedi matin uniquement.',
    receivedAt: minutesAgo(3_010),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-026',
    orderName: '#ALK-1023',
    customerName: 'Matar Diop',
    customerPhone: '+221 70 908 36 14',
    region: 'Kolda',
    amount: { value: '27400', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme apres la deuxieme relance.',
    receivedAt: minutesAgo(3_180),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-027',
    orderName: '#ALK-1022',
    customerName: 'Yacine Mbengue',
    customerPhone: '+221 76 310 20 05',
    region: 'Dakar',
    amount: { value: '183000', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'free_text',
    lastCustomerMessage: 'Je veux ajouter un deuxieme article avant expedition. Merci de me rappeler.',
    receivedAt: minutesAgo(3_360),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-028',
    orderName: '#ALK-1021',
    customerName: 'Saliou Wade',
    customerPhone: '+221 77 040 77 99',
    region: 'Saint-Louis',
    amount: { value: '24800', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(3_540),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-029',
    orderName: '#ALK-1020',
    customerName: 'Nafi Toure',
    customerPhone: '',
    region: 'Sedhiou',
    amount: { value: '11400', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'invalid_number',
    lastCustomerMessage: 'Telephone signale comme impossible a normaliser.',
    receivedAt: minutesAgo(3_740),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-030',
    orderName: '#ALK-1019',
    customerName: 'Moussa Sakho',
    customerPhone: '+221 75 672 12 84',
    region: 'Dakar',
    amount: { value: '72500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme, mais le livreur doit appeler avant de venir.',
    receivedAt: minutesAgo(3_960),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-031',
    orderName: '#ALK-1018',
    customerName: 'Ndella Faye',
    customerPhone: '+221 78 610 41 55',
    region: 'Thies',
    amount: { value: '33500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je confirme pour la commande, mais pas avant la fin du mois.',
    receivedAt: minutesAgo(4_260),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-032',
    orderName: '#ALK-1017',
    customerName: 'Lamine Cisse',
    customerPhone: '+221 70 503 99 18',
    region: 'Dakar',
    amount: { value: '14750', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'sms_only',
    lastCustomerMessage: '',
    receivedAt: minutesAgo(4_580),
    customerConfirmationStatus: 'sms_only',
    capabilities: { canConfirm: false, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-033',
    orderName: '#ALK-1016',
    customerName: 'Fama Diallo',
    customerPhone: '+221 77 830 51 46',
    region: 'Kaolack',
    amount: { value: '9300', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Erreur sur le prenom, mettez Fama Diallo sur le colis.',
    receivedAt: minutesAgo(4_920),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
  {
    id: 'mock-order-034',
    orderName: '#ALK-1015',
    customerName: 'Mor Tine',
    customerPhone: '',
    region: 'Kaffrine',
    amount: { value: '62000', currency: 'XOF' },
    isCashOnDelivery: false,
    reason: 'invalid_number',
    lastCustomerMessage: 'Plusieurs numeros detectes dans le champ telephone.',
    receivedAt: minutesAgo(5_280),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: false, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-035',
    orderName: '#ALK-1014',
    customerName: 'Seynabou Ka',
    customerPhone: '+221 76 240 18 70',
    region: 'Dakar',
    amount: { value: '40500', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'late_confirm',
    lastCustomerMessage: 'Je confirme tardivement, gardez ma commande.',
    receivedAt: minutesAgo(5_660),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: false, canCancel: true },
  },
  {
    id: 'mock-order-036',
    orderName: '#ALK-1013',
    customerName: 'Assane Gomis',
    customerPhone: '+221 77 105 64 37',
    region: 'Ziguinchor',
    amount: { value: '21900', currency: 'XOF' },
    isCashOnDelivery: true,
    reason: 'free_text',
    lastCustomerMessage: 'Je confirme si vous pouvez expedier par bus demain matin.',
    receivedAt: minutesAgo(6_020),
    customerConfirmationStatus: 'needs_attention',
    capabilities: { canConfirm: true, canRemind: true, canCancel: true },
  },
]

const emptyCounts = (): AttentionCounts => ({
  all: 0,
  free_text: 0,
  sms_only: 0,
  invalid_number: 0,
  late_confirm: 0,
})

const delay = () => new Promise(resolve => window.setTimeout(resolve, 180))

const buildCounts = (orders: AttentionOrder[]) =>
  orders.reduce((counts, order) => {
    counts.all += 1
    counts[order.reason] += 1
    return counts
  }, emptyCounts())

const removeOrders = (orderIds: string[]) => {
  const ids = new Set(orderIds)
  mockOrders = mockOrders.filter(order => !ids.has(order.id))
}

const bulkSuccess = (orderIds: string[]): BulkOrderResult => ({
  data: {
    requested: orderIds.length,
    succeeded: orderIds.map(orderId => ({ orderId })),
    failed: [],
    summary: {
      succeeded: orderIds.length,
      failed: 0,
    },
  },
})

export const mockAttentionService = {
  async list(params: AttentionQueueParams): Promise<AttentionQueueResponse> {
    await delay()

    const limit = params.limit || 20
    const page = params.page || 1
    const filtered = params.reason
      ? mockOrders.filter(order => order.reason === params.reason)
      : [...mockOrders]
    const offset = (page - 1) * limit

    return {
      data: filtered.slice(offset, offset + limit),
      counts: buildCounts(mockOrders),
      pagination: {
        page,
        limit,
        total: filtered.length,
        pages: Math.ceil(filtered.length / limit),
      },
    }
  },

  async confirm(orderId: string) {
    await delay()
    removeOrders([orderId])
    return { data: { orderId } }
  },

  async remind(orderId: string) {
    await delay()
    mockOrders = mockOrders.map(order =>
      order.id === orderId
        ? { ...order, receivedAt: new Date().toISOString(), capabilities: { ...order.capabilities, canRemind: false } }
        : order,
    )
    return { data: { orderId } }
  },

  async cancel(orderId: string, _reason: string) {
    await delay()
    removeOrders([orderId])
    return { data: { orderId } }
  },

  async bulkConfirm(orderIds: string[]) {
    await delay()
    removeOrders(orderIds)
    return bulkSuccess(orderIds)
  },

  async bulkRemind(orderIds: string[]) {
    await delay()
    mockOrders = mockOrders.map(order =>
      orderIds.includes(order.id)
        ? { ...order, receivedAt: new Date().toISOString(), capabilities: { ...order.capabilities, canRemind: false } }
        : order,
    )
    return bulkSuccess(orderIds)
  },
}
